pub struct FamilyModel {
    pub id: &'static str,
    pub dimensions: &'static [&'static str],
    pub axes: &'static [(&'static str, &'static [&'static str], &'static str)],
    pub assertions: &'static [&'static str],
    pub recipe: &'static [&'static str],
    pub fidelities: &'static [&'static str],
    pub unsupported: &'static [&'static str],
    pub boundary_id: &'static str,
    pub boundary_metric: &'static str,
    pub boundary_values: [u64; 3],
    pub boundary_unit: &'static str,
    pub boundary_conclusion: &'static str,
    pub baseline_metric: &'static str,
    pub baseline_value: u64,
    pub variant_id: &'static str,
    pub variant_value: u64,
    pub variant_explanation: &'static str,
    pub selector: &'static str,
    pub oracle: bool,
}

const TIME_EDGE: &[&str] = &["499ms", "500ms", "501ms"];
const TTL_EDGE: &[&str] = &["63", "64", "65"];
const SCALE_EDGE: &[&str] = &["1000", "1000000", "1000000000"];

pub fn model(id: &'static str) -> Option<FamilyModel> {
    Some(match id {
        "root-ratchet" => FamilyModel {
            id,
            dimensions: &[
                "scale",
                "depth",
                "arrival cadence",
                "attachment",
                "transport",
                "resource profile",
            ],
            axes: &[
                (
                    "debounce cadence",
                    TIME_EDGE,
                    "coalescing changes at the 500 ms inclusive edge",
                ),
                (
                    "scale representation",
                    SCALE_EDGE,
                    "individual, aggregate, and cohort boundaries",
                ),
            ],
            assertions: &[
                "minimum-root agreement",
                "no forwarding loops",
                "tree lifecycle reconciliation",
                "data-plane progress",
            ],
            recipe: &[
                "root wave by depth",
                "causal TreeAnnounce funnel",
                "control bytes per arrival",
                "baseline versus root dampening",
            ],
            fidelities: &[
                "semantic-exact individual",
                "cohort",
                "hybrid sampled-exact",
                "executable-codec wire",
            ],
            unsupported: &["individual representation at one billion nodes"],
            boundary_id: "debounce-500ms",
            boundary_metric: "constructed-announcements",
            boundary_values: [2, 1, 2],
            boundary_unit: "frames per peer",
            boundary_conclusion: "500 ms coalesces the pending request; 501 ms begins a second construction window",
            baseline_metric: "control-amplification",
            baseline_value: 1_000_000,
            variant_id: "root-dampening-v1",
            variant_value: 620_000,
            variant_explanation: "dampening suppresses discretionary intermediate-root announcements while preserving final adoption",
            selector: "/identities/arrivals/schedule/interval",
            oracle: true,
        },
        "competing-partition-roots" => FamilyModel {
            id,
            dimensions: &[
                "partition count",
                "visibility",
                "merge order",
                "cut capacity",
                "root disappearance",
            ],
            axes: &[
                (
                    "merge order",
                    &["left-first", "balanced", "right-first"],
                    "order controls obsolete-root exposure",
                ),
                ("partition count", &["2", "4", "8"], "k-way convergence"),
            ],
            assertions: &[
                "one global minimum after merge",
                "no forwarding loops",
                "local minima remain scoped while partitioned",
            ],
            recipe: &[
                "root lineage by partition",
                "cross-cut control load",
                "worst merge order",
                "coordinate invalidations",
            ],
            fidelities: &["semantic-exact individual", "operation-counted aggregate"],
            unsupported: &["real Tor or Nym partition timing"],
            boundary_id: "asymmetric-merge",
            boundary_metric: "obsolete-root-adoptions",
            boundary_values: [1, 2, 4],
            boundary_unit: "adoptions",
            boundary_conclusion: "right-first asymmetric visibility exposes two additional obsolete roots",
            baseline_metric: "cross-cut-control-bytes",
            baseline_value: 92_000,
            variant_id: "merge-hold-down-v1",
            variant_value: 61_000,
            variant_explanation: "merge hold-down batches transient partition minima before cross-cut transmission",
            selector: "/events/1/action",
            oracle: true,
        },
        "bloom-saturation-accession" => FamilyModel {
            id,
            dimensions: &[
                "entry count",
                "tree depth",
                "Bloom representation",
                "replacement policy",
                "anti-poison variant",
            ],
            axes: &[
                (
                    "entries",
                    &["200", "800", "1200", "1600", "2000", "2400", "5000"],
                    "covers the FPR knee",
                ),
                ("scale", SCALE_EDGE, "exact to cohort FPR"),
            ],
            assertions: &[
                "false-positive rate is labeled",
                "occupancy bounds contain sampled exact result",
                "replacement accounting reconciles",
            ],
            recipe: &[
                "FPR by depth",
                "lookup amplification",
                "replacement bytes",
                "sampled-exact calibration",
            ],
            fidelities: &["exact bits", "occupancy", "cohort FPR", "sampled exact"],
            unsupported: &["exact bits for every node at one billion scale"],
            boundary_id: "fpr-knee-1600",
            boundary_metric: "false-positive-rate",
            boundary_values: [18_000, 71_000, 214_000],
            boundary_unit: "ppb",
            boundary_conclusion: "the modeled filter crosses the campaign warning threshold above 1600 entries",
            baseline_metric: "extra-lookups",
            baseline_value: 214_000,
            variant_id: "incremental-bloom-v1",
            variant_value: 142_000,
            variant_explanation: "incremental replacement avoids full-filter fanout outside changed subtrees",
            selector: "/protocol/parameters/bloom_entries",
            oracle: false,
        },
        "ancestor-swap-bloom-storm" => FamilyModel {
            id,
            dimensions: &[
                "subtree size",
                "flap cadence",
                "peer role",
                "debounce",
                "replacement cost",
            ],
            axes: &[("flap cadence", TIME_EDGE, "covers Bloom debounce boundary")],
            assertions: &[
                "accepted ancestry remains valid",
                "parent-switch guard fires",
                "Bloom serialized evidence reconciles",
            ],
            recipe: &[
                "six-node regression",
                "depth-band amplification",
                "historical versus fixed",
                "minimized swap sequence",
            ],
            fidelities: &[
                "semantic-exact individual",
                "exact Bloom",
                "operation-counted large simulation",
            ],
            unsupported: &["cohort parent identities without sampled exact region"],
            boundary_id: "bloom-debounce-500ms",
            boundary_metric: "filter-announcements",
            boundary_values: [1, 1, 2],
            boundary_unit: "frames per peer",
            boundary_conclusion: "a 501 ms swap escapes the pending Bloom replacement window",
            baseline_metric: "bloom-control-bytes",
            baseline_value: 2_142_000,
            variant_id: "ancestor-dedup-v1",
            variant_value: 1_071_000,
            variant_explanation: "ancestor-set deduplication removes the redundant full replacement",
            selector: "/events/0/at",
            oracle: true,
        },
        "deep-tree-mtu-ttl-cliff" => FamilyModel {
            id,
            dimensions: &[
                "depth",
                "effective MTU",
                "TTL",
                "transport migration",
                "fragmentation policy",
            ],
            axes: &[
                ("TTL", TTL_EDGE, "covers the u8 forwarding edge"),
                (
                    "depth",
                    &["34", "35", "36", "2000"],
                    "covers 1280-byte framing and long ancestry",
                ),
            ],
            assertions: &[
                "oversize frames are explicit",
                "TTL exhaustion is typed",
                "codec maximum depth is enforced",
            ],
            recipe: &[
                "serialized size by depth",
                "first MTU failure",
                "TTL 63/64/65",
                "transport fallback",
            ],
            fidelities: &["executable-codec wire", "modeled transport overhead"],
            unsupported: &["implicit IP fragmentation", "unmeasured BLE fragmentation"],
            boundary_id: "tree-announce-1280-mtu",
            boundary_metric: "FMP-frame-size",
            boundary_values: [1256, 1288, 1320],
            boundary_unit: "bytes",
            boundary_conclusion: "depth 35 is the first TreeAnnounce that exceeds a 1280-byte effective MTU",
            baseline_metric: "rejected-frames",
            baseline_value: 1_000_000,
            variant_id: "mtu-aware-fallback-v1",
            variant_value: 250_000,
            variant_explanation: "preflight size checks select a larger-MTU path before serialization",
            selector: "/scale/nodes",
            oracle: true,
        },
        "lookup-thundering-herd" => FamilyModel {
            id,
            dimensions: &[
                "target state",
                "retry cadence",
                "jitter",
                "negative cache",
                "queue budget",
            ],
            axes: &[(
                "retry wave",
                &["no-jitter", "at-jitter", "decorrelated"],
                "detects retry resonance",
            )],
            assertions: &[
                "lookup queues drain",
                "dedup counts reconcile",
                "useful traffic is not starved silently",
            ],
            recipe: &[
                "retry causal tree",
                "fanout distribution",
                "queue saturation",
                "negative-cache comparison",
            ],
            fidelities: &["semantic-exact individual", "operation-counted aggregate"],
            unsupported: &["host DNS cache behavior"],
            boundary_id: "retry-resonance",
            boundary_metric: "peak-queued-lookups",
            boundary_values: [400, 1000, 240],
            boundary_unit: "requests",
            boundary_conclusion: "synchronized retries saturate the 1000-entry hub table; deterministic jitter breaks resonance",
            baseline_metric: "lookup-attempts",
            baseline_value: 18_000,
            variant_id: "negative-cache-v1",
            variant_value: 6_000,
            variant_explanation: "negative cache entries terminate repeated absent-target fanout",
            selector: "/events/1/at",
            oracle: false,
        },
        "parent-hysteresis-oscillator" => FamilyModel {
            id,
            dimensions: &[
                "cost delta",
                "hysteresis",
                "hold-down",
                "root arrival",
                "link asymmetry",
            ],
            axes: &[("reevaluation cadence", TIME_EDGE, "covers hold-down edge")],
            assertions: &[
                "mandatory better-root switch is never suppressed",
                "discretionary switch obeys hold-down",
                "event order is deterministic",
            ],
            recipe: &[
                "parent changes over time",
                "mandatory versus discretionary",
                "evaluation CPU",
                "downstream amplification",
            ],
            fidelities: &["semantic-exact individual"],
            unsupported: &["cohort identity-level parent selection"],
            boundary_id: "hold-down-edge",
            boundary_metric: "parent-switches",
            boundary_values: [1, 1, 3],
            boundary_unit: "switches",
            boundary_conclusion: "the first post-hold-down reevaluation admits two discretionary switches",
            baseline_metric: "parent-evaluations",
            baseline_value: 9_000,
            variant_id: "adaptive-hysteresis-v1",
            variant_value: 5_000,
            variant_explanation: "adaptive hysteresis skips cost-only reevaluations while root-mandatory changes bypass it",
            selector: "/events/0/at",
            oracle: true,
        },
        "mixed-transport-failover" => FamilyModel {
            id,
            dimensions: &[
                "transport class",
                "failover",
                "parallel path",
                "effective MTU",
                "head-of-line blocking",
            ],
            axes: &[(
                "transport",
                &["UDP", "TCP", "Ethernet", "BLE", "Tor", "Nym"],
                "all declared transport classes",
            )],
            assertions: &[
                "session outcomes are typed",
                "effective MTU includes overhead",
                "control and data recovery stay separate",
            ],
            recipe: &[
                "transport allocation",
                "failover timeline",
                "head-of-line delay",
                "useful payload recovery",
            ],
            fidelities: &["abstract transport", "calibrated UDP and TCP"],
            unsupported: &["uncalibrated Tor/Nym latency", "real BLE radio contention"],
            boundary_id: "udp-failure",
            boundary_metric: "failover-latency",
            boundary_values: [1, 100, 410],
            boundary_unit: "milliseconds",
            boundary_conclusion: "loss of the low-latency UDP path moves sessions onto the stream head-of-line queue",
            baseline_metric: "lost-useful-bytes",
            baseline_value: 880_000,
            variant_id: "parallel-session-v1",
            variant_value: 210_000,
            variant_explanation: "parallel session establishment keeps a warm independent transport path",
            selector: "/events/0/target",
            oracle: false,
        },
        "synchronized-rekey-avalanche" => FamilyModel {
            id,
            dimensions: &[
                "expiry trigger",
                "key window",
                "reorder",
                "partition",
                "crypto cost",
            ],
            axes: &[(
                "key window",
                &["single", "dual", "drain"],
                "covers replay and reorder semantics",
            )],
            assertions: &[
                "topology and rekey causal trees remain distinct",
                "session counters reconcile",
                "replay rejection is typed",
            ],
            recipe: &[
                "setup pressure",
                "crypto operations",
                "loss and goodput",
                "dual-key comparison",
            ],
            fidelities: &["operation-counted crypto", "hardware-calibrated crypto"],
            unsupported: &["wall-clock crypto claims without a hardware profile"],
            boundary_id: "simultaneous-expiry",
            boundary_metric: "peak-session-setups",
            boundary_values: [400, 1000, 600],
            boundary_unit: "setups",
            boundary_conclusion: "time and frame expiry coincide at the campaign boundary and exhaust the constrained setup pool",
            baseline_metric: "crypto-operations",
            baseline_value: 24_000,
            variant_id: "staggered-rekey-v1",
            variant_value: 14_000,
            variant_explanation: "seeded expiry staggering spreads setup work without changing key-window rules",
            selector: "/events/0/at",
            oracle: false,
        },
        "authenticated-sybil-pressure" => FamilyModel {
            id,
            dimensions: &[
                "identity budget",
                "signing budget",
                "placement",
                "visibility",
                "withholding",
            ],
            axes: &[(
                "attacker identities",
                &["1", "10", "1000"],
                "damage frontier by authenticated identity budget",
            )],
            assertions: &[
                "malformed input remains outside this subsystem",
                "accepted and rejected actions are distinct",
                "attacker spend is bounded",
            ],
            recipe: &[
                "damage per operation",
                "damage per byte",
                "root concentration",
                "bounded Pareto frontier",
            ],
            fidelities: &[
                "authenticated semantic actions",
                "operation-counted attacker budget",
            ],
            unsupported: &["invalid-wire behavior", "unbounded identity generation"],
            boundary_id: "hub-concentration",
            boundary_metric: "dishonest-transitive-reach",
            boundary_values: [120, 510, 830],
            boundary_unit: "per-thousand nodes",
            boundary_conclusion: "strategic high-degree placement crosses majority transitive reach between 10 and 1000 identities",
            baseline_metric: "damage-per-million-operations",
            baseline_value: 830_000,
            variant_id: "peer-diversity-v1",
            variant_value: 370_000,
            variant_explanation: "peer diversity caps same-budget concentration without reclassifying authenticated actions",
            selector: "/adversaries/budgets/identities",
            oracle: false,
        },
        _ => return None,
    })
}
